version: '3.5'


volumes:
  postgres:
    external: true
  pgadmin:
    external: true

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5433"
    volumes:
      - postgres:/var/lib/postgresql/data
